steps:
- bash: |
    source activate foo
    env
    make install CC=$CC CFLAGS="$CFLAGS -O3 -Wall -I$CONDA_PREFIX/include" LIBS="-L$CONDA_PREFIX/lib" prefix=$CONDA_PREFIX/bin
  displayName: Installing methylDackel
- bash: |
    source activate foo
    export LD_LIBRARY_PATH=$CONDA_PREFIX/lib
    make test CC=$CC CFLAGS="-O3 -Wall -I$CONDA_PREFIX/include" LIBS="-L$CONDA_PREFIX/lib"
  displayName: Test methylDackel
